// ============================================================================
//  ENCOUNTERS — edit this file to add, change, or remove DnD-style text events.
// ============================================================================
//
//  HOW TO EDIT
//  -----------
//  • Each entry is `key: { title, start, nodes }`. Biomes (content/biomes.ts) list
//    which encounter keys they draw from.
//  • A node has `text` (narration) and optional `choices`. No choices = the encounter
//    ends at that node. The run reaches a checkpoint after the floor's last room.
//  • A choice with a `stat` is a check: on success it goes to `goSuccess`, on fail to
//    `goFail`; `successText`/`failText` are the result lines. A choice without a stat
//    just goes to `go`. `difficulty` ~3–8 (higher = harder), measured in stat levels. Tune freely.
//  • Loot/heals: `reward` (always) / `rewardOnSuccess`; `hpOnFail` (damage on a miss);
//    `hpOnSuccess` / `staOnSuccess` / `mpOnSuccess` (restore on a hit). Material keys
//    come from content/materials.ts.
// ============================================================================
import type { EncounterDef } from '@/engine/encounters';

export const ENCOUNTERS: Record<string, EncounterDef> = {
  // --- Catacombs ----------------------------------------------------------
  sealed_door: {
    key: 'sealed_door',
    title: 'The Sealed Door',
    start: 'door',
    nodes: {
      door: {
        id: 'door',
        text: 'A door of black iron, sealed with shifting runes, blocks the passage.',
        choices: [
          {
            label: 'Decipher the runes (Knowledge)',
            stat: 'KN',
            difficulty: 5,
            goSuccess: 'opened',
            goFail: 'locked',
            successText: 'The glyphs align and the bolts slide free.',
            failText: 'A glyph flares and lashes you with arcane backlash.',
            rewardOnSuccess: { gold: 30, materials: { crystals: 1 } },
            hpOnFail: -8,
          },
          {
            label: 'Wrench it open (Strength)',
            stat: 'ST',
            difficulty: 7,
            goSuccess: 'forced',
            goFail: 'locked',
            successText: 'Hinges scream and give way.',
            failText: 'The iron holds; you wrench your shoulder against it.',
            rewardOnSuccess: { gold: 20, materials: { iron_bar: 1 } },
            hpOnFail: -10,
          },
        ],
      },
      locked: {
        id: 'locked',
        text: 'Still sealed, the door mocks you. There must be another way through.',
        choices: [
          {
            label: 'Search for a hidden catch (Dexterity)',
            stat: 'DX',
            difficulty: 5,
            goSuccess: 'opened',
            goFail: 'giveup',
            successText: 'Your fingers find a recessed catch — click.',
            failText: 'Nothing. You squeeze through a crack instead, scraping skin.',
            rewardOnSuccess: { gold: 25 },
            hpOnFail: -6,
          },
          { label: 'Leave it and move on', go: 'giveup', successText: 'You abandon the door and press deeper.' },
        ],
      },
      opened: { id: 'opened', text: "Beyond lies a scholar's cache, long undisturbed." },
      forced: { id: 'forced', text: 'The way is open — and a fallen pack spills its contents at your feet.' },
      giveup: { id: 'giveup', text: "You move on, the cache's secrets left behind in the dark." },
    },
  },

  gatekeeper: {
    key: 'gatekeeper',
    title: 'The Gatekeeper',
    start: 'meet',
    nodes: {
      meet: {
        id: 'meet',
        text: "A spectral gatekeeper bars the way. 'A toll,' it intones, 'or a clever tongue.'",
        choices: [
          {
            label: 'Charm it (Charisma)',
            stat: 'CH',
            difficulty: 5,
            goSuccess: 'passed',
            goFail: 'angered',
            successText: 'Flattery softens the wraith; it waves you through.',
            failText: 'Your words ring hollow. It bristles with cold light.',
            rewardOnSuccess: { gold: 40 },
          },
          {
            label: 'Reason with it (Wisdom)',
            stat: 'WI',
            difficulty: 6,
            goSuccess: 'passed',
            goFail: 'angered',
            successText: 'You name the old compact; bound by it, the gatekeeper yields.',
            failText: 'It rejects your logic with a hollow laugh.',
            rewardOnSuccess: { gold: 35, materials: { crystals: 1 } },
          },
        ],
      },
      angered: {
        id: 'angered',
        text: 'The gatekeeper raises a spectral blade. This is your last chance.',
        choices: [
          {
            label: 'Slip past it (Agility)',
            stat: 'AG',
            difficulty: 6,
            goSuccess: 'passed',
            goFail: 'struck',
            successText: 'You dart through the gate before it can react.',
            failText: 'It catches you a glancing blow as you bolt through.',
            hpOnFail: -12,
          },
          {
            label: 'Force the gate (Strength)',
            stat: 'ST',
            difficulty: 7,
            goSuccess: 'forced',
            goFail: 'struck',
            successText: 'You batter the gate from its hinges.',
            failText: "The wraith's blade bites deep before you break through.",
            rewardOnSuccess: { materials: { bronze_bar: 1 } },
            hpOnFail: -14,
          },
        ],
      },
      passed: { id: 'passed', text: 'The gate swings open without a fight.' },
      forced: { id: 'forced', text: 'You break through, the gatekeeper howling into silence behind you.' },
      struck: { id: 'struck', text: 'Bloodied, you stumble past as the apparition fades.' },
    },
  },

  bone_pit: {
    key: 'bone_pit',
    title: 'The Bone Pit',
    start: 'pit',
    nodes: {
      pit: {
        id: 'pit',
        text: 'The floor gives way into a pit of clattering bones that drag at your limbs.',
        choices: [
          {
            label: 'Power through the morass (Endurance)',
            stat: 'EN',
            difficulty: 5,
            goSuccess: 'climbed',
            goFail: 'sinking',
            successText: 'Lungs burning, you haul yourself free.',
            failText: 'The bones drag you down into the cold heap.',
            rewardOnSuccess: { gold: 20, materials: { herbs: 1 } },
            hpOnFail: -8,
          },
          {
            label: 'Pick a careful path (Dexterity)',
            stat: 'DX',
            difficulty: 6,
            goSuccess: 'climbed',
            goFail: 'sinking',
            successText: 'You step from skull to skull and cross clean.',
            failText: 'A footing crumbles and you plunge in.',
            rewardOnSuccess: { gold: 25 },
            hpOnFail: -10,
          },
        ],
      },
      sinking: {
        id: 'sinking',
        text: 'Chest-deep and sinking, you need to get out — now.',
        choices: [
          {
            label: 'Thrash free by main strength (Strength)',
            stat: 'ST',
            difficulty: 5,
            goSuccess: 'climbed',
            goFail: 'crawl',
            successText: 'You burst out in a shower of bone.',
            failText: 'You barely crawl free, wrung out.',
            hpOnFail: -6,
            staDelta: -2,
          },
          {
            label: 'Stay calm and let the bones settle (Wisdom)',
            stat: 'WI',
            difficulty: 4,
            goSuccess: 'climbed',
            goFail: 'crawl',
            successText: 'You still yourself and rise; the heap releases you.',
            failText: 'Panic wins; you flounder out the hard way.',
            hpOnFail: -6,
          },
        ],
      },
      climbed: { id: 'climbed', text: 'You reach solid ground, a relic clutched from the bones.' },
      crawl: { id: 'crawl', text: 'You drag yourself out, rattled and empty-handed.' },
    },
  },

  // --- Overgrown Ruins ----------------------------------------------------
  collapsing_bridge: {
    key: 'collapsing_bridge',
    title: 'The Collapsing Bridge',
    start: 'bridge',
    nodes: {
      bridge: {
        id: 'bridge',
        text: "A rope bridge spans a ravine — and it's coming apart the moment you step on.",
        choices: [
          {
            label: 'Sprint across (Agility)',
            stat: 'AG',
            difficulty: 6,
            goSuccess: 'across',
            goFail: 'falling',
            successText: 'You race the collapse and leap to safety.',
            failText: 'A plank snaps underfoot and you drop.',
            rewardOnSuccess: { gold: 25, materials: { cloth_roll: 1 } },
            hpOnFail: -10,
          },
          {
            label: 'Cross carefully, plank by plank (Dexterity)',
            stat: 'DX',
            difficulty: 5,
            goSuccess: 'across',
            goFail: 'falling',
            successText: 'Sure-footed, you pick your way over.',
            failText: 'The boards give way beneath you.',
            rewardOnSuccess: { gold: 20 },
            hpOnFail: -8,
          },
        ],
      },
      falling: {
        id: 'falling',
        text: 'You dangle over the ravine, one hand on a fraying rope.',
        choices: [
          {
            label: 'Haul yourself up (Strength)',
            stat: 'ST',
            difficulty: 5,
            goSuccess: 'across',
            goFail: 'drop',
            successText: 'Muscles screaming, you climb to safety.',
            failText: 'Your grip fails — you fall, catching a ledge below.',
            hpOnFail: -12,
          },
          {
            label: 'Swing to a ledge (Dexterity)',
            stat: 'DX',
            difficulty: 6,
            goSuccess: 'across',
            goFail: 'drop',
            successText: 'You swing and roll onto solid stone.',
            failText: 'You misjudge it and slam into the rock.',
            hpOnFail: -12,
          },
        ],
      },
      across: { id: 'across', text: 'You reach the far side as the bridge tumbles into the dark.' },
      drop: { id: 'drop', text: 'You land hard in the gorge and limp up the far slope.' },
    },
  },

  wild_grove: {
    key: 'wild_grove',
    title: 'The Wild Grove',
    start: 'grove',
    nodes: {
      grove: {
        id: 'grove',
        text: 'A grove pulses with old magic. A guardian dryad studies you, wary.',
        choices: [
          {
            label: 'Offer respect and parley (Charisma)',
            stat: 'CH',
            difficulty: 5,
            goSuccess: 'blessed',
            goFail: 'spurned',
            successText: "The dryad warms to you and shares the grove's gifts.",
            failText: 'It deems you false and turns its back.',
            rewardOnSuccess: { gold: 30, materials: { herbs: 2 } },
            hpOnSuccess: 10,
          },
          {
            label: "Read the grove's lore (Knowledge)",
            stat: 'KN',
            difficulty: 6,
            goSuccess: 'blessed',
            goFail: 'spurned',
            successText: 'You speak the old names; the dryad bows and gifts you.',
            failText: 'You stumble the rites and offend the guardian.',
            rewardOnSuccess: { gold: 25, materials: { herbs: 1, crystals: 1 } },
            hpOnSuccess: 10,
          },
        ],
      },
      spurned: {
        id: 'spurned',
        text: 'The dryad raises coiling vines. Make amends, or flee.',
        choices: [
          {
            label: 'Soothe it with a song (Wisdom)',
            stat: 'WI',
            difficulty: 5,
            goSuccess: 'blessed',
            goFail: 'lashed',
            successText: 'Your calm reaches it; the grove relents.',
            failText: 'The vines strike before you can finish.',
            hpOnFail: -10,
          },
          {
            label: 'Back away slowly (Agility)',
            stat: 'AG',
            difficulty: 4,
            goSuccess: 'retreat',
            goFail: 'lashed',
            successText: 'You slip out of the grove unharmed.',
            failText: 'A vine catches your ankle as you go.',
            hpOnFail: -8,
          },
        ],
      },
      blessed: { id: 'blessed', text: "The grove's light knits your wounds as you pass on." },
      retreat: { id: 'retreat', text: 'You leave the grove to its guardian, no worse for it.' },
      lashed: { id: 'lashed', text: 'Whipped by thorns, you stagger out of the grove.' },
    },
  },

  // --- Catacombs (additional) ---------------------------------------------
  ossuary_hoard: {
    key: 'ossuary_hoard',
    title: 'The Ossuary Hoard',
    start: 'hoard',
    nodes: {
      hoard: {
        id: 'hoard',
        text: 'A gilded reliquary sits half-buried in a mound of bones, its locks still intact.',
        choices: [
          {
            label: 'Pick the lock (Dexterity)',
            stat: 'DX',
            difficulty: 5,
            goSuccess: 'opened',
            goFail: 'trapped',
            successText: 'The mechanism yields to your touch — the lid swings open.',
            failText: 'A spring-loaded bone-spike fires from the lock.',
            rewardOnSuccess: { gold: 45, materials: { gemstone: 1, crystals: 1 } },
            hpOnFail: -10,
          },
          {
            label: 'Identify the sigils (Knowledge)',
            stat: 'KN',
            difficulty: 5,
            goSuccess: 'opened',
            goFail: 'trapped',
            successText: 'You read a disarm sequence into the carvings — the chest clicks open.',
            failText: 'You read the wrong rune; the chest bites back.',
            rewardOnSuccess: { gold: 50, materials: { crystals: 2 } },
            hpOnFail: -8,
          },
        ],
      },
      trapped: {
        id: 'trapped',
        text: 'Bleeding, you still have a chance to pry the reliquary free.',
        choices: [
          {
            label: 'Wrench it free (Strength)',
            stat: 'ST',
            difficulty: 6,
            goSuccess: 'rich',
            goFail: 'fled',
            successText: 'You tear the reliquary loose and pocket its contents.',
            failText: 'It holds fast — you cut your losses and move on.',
            rewardOnSuccess: { gold: 30, materials: { gemstone: 1 } },
          },
          {
            label: 'Slip out before more traps fire (Agility)',
            stat: 'AG',
            difficulty: 4,
            goSuccess: 'fled',
            goFail: 'fled',
            successText: 'You back away cleanly.',
            failText: 'You stumble back; another spike grazes you.',
            hpOnFail: -6,
          },
        ],
      },
      opened: { id: 'opened', text: "The reliquary spills its wealth into your hands." },
      rich: { id: 'rich', text: 'Bloody but richer, you press deeper.' },
      fled: { id: 'fled', text: 'The hoard stays buried. Some treasure costs too much.' },
    },
  },

  whispering_crypt: {
    key: 'whispering_crypt',
    title: 'The Whispering Crypt',
    start: 'crypt',
    nodes: {
      crypt: {
        id: 'crypt',
        text: "Dozens of voices murmur from the burial niches — the dead recounting what they knew in life. You could listen, or block it out.",
        choices: [
          {
            label: 'Open your mind to the voices (Wisdom)',
            stat: 'WI',
            difficulty: 5,
            goSuccess: 'enlightened',
            goFail: 'maddened',
            successText: 'The whispers coalesce into revelation — old knowledge, freely given.',
            failText: 'The flood of voices is too much; your thoughts fracture.',
            rewardOnSuccess: { gold: 35, materials: { crystals: 1 } },
            mpOnSuccess: 8,
            mpOnFail: -10,
          },
          {
            label: 'Intone the burial rites (Charisma)',
            stat: 'CH',
            difficulty: 5,
            goSuccess: 'appeased',
            goFail: 'maddened',
            successText: 'The dead recognise a respectful tongue and quieten gratefully.',
            failText: 'Your words grate — the whispers become a shriek.',
            rewardOnSuccess: { gold: 40 },
            mpOnSuccess: 6,
            mpOnFail: -8,
          },
        ],
      },
      maddened: {
        id: 'maddened',
        text: 'The voices overwhelm you. You need to get out — or endure.',
        choices: [
          {
            label: 'Steel yourself and push through (Endurance)',
            stat: 'EN',
            difficulty: 5,
            goSuccess: 'endured',
            goFail: 'shaken',
            successText: 'You wall off the noise and stagger out the far side.',
            failText: 'The screaming follows you out.',
            hpOnFail: -8,
          },
          {
            label: 'Sprint for the exit (Agility)',
            stat: 'AG',
            difficulty: 4,
            goSuccess: 'endured',
            goFail: 'shaken',
            successText: "You're through and out before the chorus peaks.",
            failText: 'You trip in the dark and take longer than hoped.',
            hpOnFail: -6,
          },
        ],
      },
      enlightened: { id: 'enlightened', text: "The dead's knowledge fills you like cold spring water." },
      appeased: { id: 'appeased', text: 'The crypt falls silent. A calm follows you out.' },
      endured: { id: 'endured', text: 'Rattled but whole, you clear the crypt.' },
      shaken: { id: 'shaken', text: 'You stumble out, ears still ringing.' },
    },
  },

  // --- Overgrown Ruins (additional) ----------------------------------------
  toppled_idol: {
    key: 'toppled_idol',
    title: 'The Toppled Idol',
    start: 'idol',
    nodes: {
      idol: {
        id: 'idol',
        text: "A great stone idol has fallen across the passage, its altar scattered. Coins glint in the rubble.",
        choices: [
          {
            label: 'Heave the idol upright (Strength)',
            stat: 'ST',
            difficulty: 6,
            goSuccess: 'righted',
            goFail: 'cracked',
            successText: "The idol stands again — and its altar glows with rekindled offering.",
            failText: "You strain; the idol grinds but doesn't rise.",
            rewardOnSuccess: { gold: 40, materials: { stone: 1, amber_resin: 1 } },
            hpOnFail: -8,
          },
          {
            label: "Read the idol's inscriptions (Knowledge)",
            stat: 'KN',
            difficulty: 5,
            goSuccess: 'deciphered',
            goFail: 'cracked',
            successText: "You find the idol's true name and speak it — coins rise from the dust.",
            failText: "The inscription is in a dialect you don't know.",
            rewardOnSuccess: { gold: 35, materials: { stone: 1 } },
          },
        ],
      },
      cracked: {
        id: 'cracked',
        text: "The idol offers nothing obvious. Perhaps a moment of reflection would help.",
        choices: [
          {
            label: "Offer a moment's quiet reverence (Wisdom)",
            stat: 'WI',
            difficulty: 4,
            goSuccess: 'blessed',
            goFail: 'walked_on',
            successText: "The idol acknowledges the gesture — warmth spreads through you.",
            failText: "No response. Stone is just stone.",
            hpOnSuccess: 12,
          },
          { label: 'Step past and move on', go: 'walked_on', successText: 'You leave it to its fall.' },
        ],
      },
      righted: { id: 'righted', text: 'The grove-god watches from its restored plinth. You feel watched — approvingly.' },
      deciphered: { id: 'deciphered', text: 'The coins and relics settle into your pack as you press on.' },
      blessed: { id: 'blessed', text: 'The old god, even fallen, can still bless.' },
      walked_on: { id: 'walked_on', text: 'The idol remains on its side. The passage clears ahead.' },
    },
  },

  spiders_larder: {
    key: 'spiders_larder',
    title: "The Spider's Larder",
    start: 'larder',
    nodes: {
      larder: {
        id: 'larder',
        text: "Dozens of silk-wrapped bundles hang from the ceiling — the spider's prey, preserved. Some bulge with gear.",
        choices: [
          {
            label: 'Cut bundles open quietly (Dexterity)',
            stat: 'DX',
            difficulty: 5,
            goSuccess: 'looted',
            goFail: 'swarm',
            successText: 'You work fast and silent; the silk splits and your pockets fill.',
            failText: "A bundle drops with a crash — something stirs in the dark.",
            rewardOnSuccess: { gold: 35, materials: { cloth_roll: 1, herbs: 1 } },
          },
          {
            label: "Identify which bundles look richest (Knowledge)",
            stat: 'KN',
            difficulty: 4,
            goSuccess: 'looted',
            goFail: 'swarm',
            successText: 'You read the web patterns and pick the heaviest pods.',
            failText: "Your probing disturbs the web. Skittering begins overhead.",
            rewardOnSuccess: { gold: 40, materials: { cloth_roll: 2 } },
          },
        ],
      },
      swarm: {
        id: 'swarm',
        text: "Spiderlings pour from the ceiling. Fight through or run.",
        choices: [
          {
            label: 'Endure the bites and grab what you can (Endurance)',
            stat: 'EN',
            difficulty: 5,
            goSuccess: 'escaped',
            goFail: 'bitten',
            successText: 'You take a dozen stings but come away with something.',
            failText: 'The swarm drives you back empty-handed.',
            rewardOnSuccess: { gold: 20, materials: { herbs: 1 } },
            hpOnFail: -10,
          },
          {
            label: 'Bolt for the exit (Agility)',
            stat: 'AG',
            difficulty: 5,
            goSuccess: 'escaped',
            goFail: 'bitten',
            successText: 'You outrun the swarm — barely.',
            failText: 'They catch you in the doorway.',
            hpOnFail: -12,
          },
        ],
      },
      looted: { id: 'looted', text: 'Silk-threads trailing, you slip out of the larder laden.' },
      escaped: { id: 'escaped', text: "You're out. Your pulse is still racing." },
      bitten: { id: 'bitten', text: 'Marked by a dozen bites, you stagger onward.' },
    },
  },

  // --- Overgrown Ruins (additional events) --------------------------------
  ruined_scriptorium: {
    key: 'ruined_scriptorium',
    title: 'The Ruined Scriptorium',
    start: 'scriptorium',
    nodes: {
      scriptorium: {
        id: 'scriptorium',
        text: 'A scriptorium, half swallowed by roots, still holds shelves of oilskin-wrapped tomes. The roots have been kind to the drier volumes.',
        choices: [
          {
            label: 'Decipher the academic texts (Knowledge)',
            stat: 'KN',
            difficulty: 3,
            goSuccess: 'studied',
            goFail: 'scratched',
            successText: 'You identify the most valuable treatises and tuck them away.',
            failText: 'Dense academic script defeats you. You take a random volume.',
            rewardOnSuccess: { gold: 30, materials: { crystals: 1 } },
            reward: { gold: 10 },
          },
          {
            label: 'Trust instinct — read the energy of the room (Wisdom)',
            stat: 'WI',
            difficulty: 3,
            goSuccess: 'intuited',
            goFail: 'scratched',
            successText: 'The most-read volumes glow faintly to your senses. You take the right ones.',
            failText: 'Your instinct leads you to a shelf of liturgical catalogues. Useful to no one.',
            rewardOnSuccess: { gold: 25, materials: { amber_resin: 1 } },
            hpOnSuccess: 8,
          },
        ],
      },
      scratched: {
        id: 'scratched',
        text: "You've taken something, though you're not certain what. There's still time to look around.",
        choices: [
          {
            label: 'Root through the rubble (Dexterity)',
            stat: 'DX',
            difficulty: 2,
            goSuccess: 'found_more',
            goFail: 'leave',
            successText: 'Under a fallen shelf you find a sealed case of coin.',
            failText: 'Just beetles. You pocket what you have and go.',
            rewardOnSuccess: { gold: 20 },
          },
          { label: 'Leave with what you have', go: 'leave' },
        ],
      },
      studied: { id: 'studied', text: 'You leave the scriptorium richer in coin and knowledge.' },
      intuited: { id: 'intuited', text: 'The tomes you chose pulse faintly as you carry them out.' },
      found_more: { id: 'found_more', text: 'A sealed coin-case — the scriptorium master\'s rainy-day fund.' },
      leave: { id: 'leave', text: 'The scriptorium recedes behind walls of vine.' },
    },
  },

  vine_temple: {
    key: 'vine_temple',
    title: 'The Vine-Choked Temple',
    start: 'temple',
    nodes: {
      temple: {
        id: 'temple',
        text: 'A temple exterior is barely visible beneath decades of vine growth. Its altar — and whatever was placed upon it — still stands inside.',
        choices: [
          {
            label: 'Force a path through the vines (Endurance)',
            stat: 'EN',
            difficulty: 5,
            goSuccess: 'reached',
            goFail: 'entangled',
            successText: 'You crash through and reach the altar, scratched but rewarded.',
            failText: 'The vines close around you — something scores a long scratch down your arm.',
            rewardOnSuccess: { gold: 40, materials: { herbs: 1, amber_resin: 1 } },
            hpOnFail: -10,
            curseOnFail: true,
          },
          {
            label: 'Find the old devotional path (Wisdom)',
            stat: 'WI',
            difficulty: 4,
            goSuccess: 'reached',
            goFail: 'entangled',
            successText: 'You sense where the vines thin — the old path still holds.',
            failText: 'The path you choose ends in a thorny wall.',
            rewardOnSuccess: { gold: 35, materials: { herbs: 2 } },
            hpOnFail: -8,
          },
        ],
      },
      entangled: {
        id: 'entangled',
        text: "You're caught. You need strength or speed to get free.",
        choices: [
          {
            label: 'Tear free (Strength)',
            stat: 'ST',
            difficulty: 4,
            goSuccess: 'escaped',
            goFail: 'dragged',
            successText: 'You burst loose, raking thorns, and scramble to the altar.',
            failText: "The vines hold. You're dragged backward.",
            rewardOnSuccess: { gold: 25 },
            hpOnFail: -10,
          },
          {
            label: 'Slip free (Agility)',
            stat: 'AG',
            difficulty: 5,
            goSuccess: 'escaped',
            goFail: 'dragged',
            successText: 'You twist and writhe until the vines release you.',
            failText: 'They tighten. You heave against them and eventually break free — worse for wear.',
            hpOnFail: -12,
          },
        ],
      },
      reached: { id: 'reached', text: 'The altar holds offerings untouched for generations. Not untouched for much longer.' },
      escaped: { id: 'escaped', text: 'You reach the altar bloody but determined.' },
      dragged: { id: 'dragged', text: 'The vines drag you back. You leave the temple to its verdant guardian.' },
    },
  },

  overgrown_arsenal: {
    key: 'overgrown_arsenal',
    title: 'The Overgrown Arsenal',
    start: 'arsenal',
    nodes: {
      arsenal: {
        id: 'arsenal',
        text: 'Racks of weapons slump under vine and rust. Most are worthless — but some, the ones sealed behind a barred case, are not.',
        choices: [
          {
            label: 'Break the case open (Strength)',
            stat: 'ST',
            difficulty: 7,
            goSuccess: 'looted',
            goFail: 'trapped',
            successText: 'The case shatters. Hardened steel gleams inside.',
            failText: 'A counterweight mechanism fires — a rusted bolt clips your shoulder.',
            rewardOnSuccess: { gold: 60, materials: { iron_bar: 2, bronze_bar: 1 } },
            hpOnFail: -14,
          },
          {
            label: 'Leave the dangerous-looking thing alone',
            go: 'passed',
          },
        ],
      },
      trapped: {
        id: 'trapped',
        text: "Bleeding, the case hangs open a crack. Still reachable — if you're quick.",
        choices: [
          {
            label: 'Dart in and grab what you can (Agility)',
            stat: 'AG',
            difficulty: 5,
            goSuccess: 'partial',
            goFail: 'gave_up',
            successText: 'You snatch an armful and retreat before the second bolt fires.',
            failText: "The click of another mechanism sends you stumbling back empty-handed.",
            rewardOnSuccess: { gold: 30, materials: { iron_bar: 1 } },
          },
          { label: 'Give up and move on', go: 'gave_up' },
        ],
      },
      looted: { id: 'looted', text: 'A genuine haul — the arsenal\'s finest, preserved against all expectation.' },
      partial: { id: 'partial', text: 'Not everything, but enough. You retreat before the arsenal decides you\'ve had enough.' },
      passed: { id: 'passed', text: 'A wise choice. The arsenal stays intact — and so do you.' },
      gave_up: { id: 'gave_up', text: 'Empty-handed, but alive. Sometimes that\'s the win.' },
    },
  },

  riverside_shrine: {
    key: 'riverside_shrine',
    title: 'The Riverside Shrine',
    start: 'shrine',
    nodes: {
      shrine: {
        id: 'shrine',
        text: 'A small shrine stands at the edge of an underground stream, its spirit-candles somehow still lit. The water-god here is old and listening.',
        choices: [
          {
            label: 'Kneel and pray for a blessing (Wisdom)',
            stat: 'WI',
            difficulty: 5,
            goSuccess: 'blessed',
            goFail: 'silence',
            successText: 'The candles flare. Something warm moves through you — and settles.',
            failText: 'The shrine is quiet. The god does not answer.',
            boonOnSuccess: 1,
          },
          {
            label: 'Speak the old water rites (Charisma)',
            stat: 'CH',
            difficulty: 5,
            goSuccess: 'favoured',
            goFail: 'silence',
            successText: 'You speak the rites correctly. The stream stills and offers.',
            failText: 'You stumble the words. The stream flows on, unmoved.',
            rewardOnSuccess: { gold: 35, materials: { herbs: 1 } },
            hpOnSuccess: 12,
          },
        ],
      },
      silence: {
        id: 'silence',
        text: "The shrine gave nothing. But the stream is still clear and cold — you could rest here a moment.",
        choices: [
          {
            label: 'Drink and rest (Endurance)',
            stat: 'EN',
            difficulty: 3,
            goSuccess: 'rested',
            goFail: 'cold',
            successText: 'The cold water revives you. You rise steadier.',
            failText: 'The cold gives you no comfort.',
            hpOnSuccess: 10,
            staOnSuccess: 2,
          },
          { label: 'Move on', go: 'cold' },
        ],
      },
      blessed: { id: 'blessed', text: 'Something has settled on your shoulders — a weight, but not an unwelcome one. The shrine\'s blessing travels with you.' },
      favoured: { id: 'favoured', text: 'The god nods. Your offering rises from the stream and fills your hands.' },
      rested: { id: 'rested', text: 'Cold water, still air. You move on renewed.' },
      cold: { id: 'cold', text: 'The shrine fades behind you, its candles still lit.' },
    },
  },

  fungal_network: {
    key: 'fungal_network',
    title: 'The Fungal Network',
    start: 'network',
    nodes: {
      network: {
        id: 'network',
        text: "A vast network of luminous fungi carpets the ruins' floor, pulsing gently. Disturbing them would be loud. Harvesting them carefully could be valuable.",
        choices: [
          {
            label: 'Harvest carefully (Dexterity)',
            stat: 'DX',
            difficulty: 4,
            goSuccess: 'harvested',
            goFail: 'disturbed',
            successText: 'You cut the stalks cleanly. The network barely shivers.',
            failText: 'A cluster pops under your boot. The whole floor pulses in alarm.',
            rewardOnSuccess: { materials: { herbs: 2, amber_resin: 1 }, gold: 20 },
            hpOnFail: -8,
          },
          {
            label: 'Study the growth patterns (Knowledge)',
            stat: 'KN',
            difficulty: 4,
            goSuccess: 'identified',
            goFail: 'disturbed',
            successText: 'You identify the medicinal strains and harvest them precisely.',
            failText: 'Confused by the species variety, you grab a cluster that spores aggressively.',
            rewardOnSuccess: { materials: { herbs: 3 }, gold: 15 },
            hpOnFail: -6,
          },
        ],
      },
      disturbed: {
        id: 'disturbed',
        text: "The fungi pulse louder, attracting attention. Move fast.",
        choices: [
          {
            label: 'Sprint out before anything arrives (Agility)',
            stat: 'AG',
            difficulty: 4,
            goSuccess: 'escaped',
            goFail: 'cornered',
            successText: "You're out before the first growl reaches the chamber.",
            failText: "Not fast enough. You fight your way through.",
            hpOnFail: -10,
          },
        ],
      },
      harvested: { id: 'harvested', text: 'Your pack is heavier and the network still glows peacefully.' },
      identified: { id: 'identified', text: 'The rarest varieties are now in your satchel.' },
      escaped: { id: 'escaped', text: 'You burst out into the corridor just ahead of the noise.' },
      cornered: { id: 'cornered', text: 'Battered but through it. The fungi glow behind you in quiet accusation.' },
    },
  },

  // --- Frozen Caverns -----------------------------------------------------
  frozen_chasm: {
    key: 'frozen_chasm',
    title: 'The Frozen Chasm',
    start: 'chasm',
    nodes: {
      chasm: {
        id: 'chasm',
        text: 'A glacier-cut chasm yawns ahead, wind howling with killing cold.',
        choices: [
          {
            label: 'Leap the gap (Strength)',
            stat: 'ST',
            difficulty: 6,
            goSuccess: 'crossed',
            goFail: 'slipped',
            successText: 'You clear the chasm and roll to a stop.',
            failText: 'You come up short, slamming into the ice wall.',
            rewardOnSuccess: { gold: 25, materials: { crystals: 1 } },
            hpOnFail: -12,
          },
          {
            label: 'Endure the cold and climb around (Endurance)',
            stat: 'EN',
            difficulty: 5,
            goSuccess: 'crossed',
            goFail: 'slipped',
            successText: 'Numb but unbroken, you work your way across.',
            failText: 'The cold saps you; you barely reach a ledge.',
            rewardOnSuccess: { gold: 20 },
            hpOnFail: -8,
            staDelta: -2,
          },
        ],
      },
      slipped: {
        id: 'slipped',
        text: 'Clinging to sheer ice, you must move before the cold claims you.',
        choices: [
          {
            label: 'Find handholds and climb (Dexterity)',
            stat: 'DX',
            difficulty: 5,
            goSuccess: 'crossed',
            goFail: 'frostbit',
            successText: 'Inch by inch, you climb to safety.',
            failText: 'Your fingers fail; you drop to a lower shelf.',
            hpOnFail: -10,
          },
          {
            label: 'Will yourself through the pain (Wisdom)',
            stat: 'WI',
            difficulty: 5,
            goSuccess: 'crossed',
            goFail: 'frostbit',
            successText: 'You focus past the cold and pull through.',
            failText: 'The cold wins this round.',
            hpOnFail: -10,
          },
        ],
      },
      crossed: { id: 'crossed', text: 'You reach the far rim, breath steaming in the still air.' },
      frostbit: { id: 'frostbit', text: 'Frostbitten and shaking, you crawl onward.' },
    },
  },

  starving_dark: {
    key: 'starving_dark',
    title: 'The Frozen Shrine',
    start: 'shrine',
    nodes: {
      shrine: {
        id: 'shrine',
        text: 'In a still hollow you find a frozen shrine, ringed by the bones of those who failed here.',
        choices: [
          {
            label: 'Forage the hollow for supplies (Knowledge)',
            stat: 'KN',
            difficulty: 5,
            goSuccess: 'supplied',
            goFail: 'empty',
            successText: 'You find cached rations and herbs, still good.',
            failText: 'Nothing but ice and old bones.',
            rewardOnSuccess: { materials: { herbs: 2 } },
            hpOnSuccess: 15,
          },
          {
            label: 'Pray at the shrine (Wisdom)',
            stat: 'WI',
            difficulty: 5,
            goSuccess: 'blessed',
            goFail: 'empty',
            successText: 'A faint warmth answers — the shrine restores you.',
            failText: 'The shrine is silent and dead.',
            hpOnSuccess: 12,
            mpOnSuccess: 6,
          },
        ],
      },
      empty: {
        id: 'empty',
        text: 'Cold and empty-handed, you search for any way onward.',
        choices: [
          {
            label: 'Rest a moment to gather strength (Endurance)',
            stat: 'EN',
            difficulty: 4,
            goSuccess: 'rested',
            goFail: 'weary',
            successText: 'A brief rest steadies you.',
            failText: "There's no rest to be had in this cold.",
            hpOnSuccess: 10,
            staOnSuccess: 2,
          },
          { label: 'Push on immediately', go: 'weary', successText: 'You waste no time and move deeper.' },
        ],
      },
      supplied: { id: 'supplied', text: 'Restored, you shoulder your finds and go on.' },
      blessed: { id: 'blessed', text: 'Renewed, you leave the shrine to the dark.' },
      rested: { id: 'rested', text: 'Steadier now, you press into the cold.' },
      weary: { id: 'weary', text: 'Weary but alive, you continue.' },
    },
  },

  // --- Frozen Caverns (additional) ----------------------------------------
  buried_caravan: {
    key: 'buried_caravan',
    title: 'The Buried Caravan',
    start: 'caravan',
    nodes: {
      caravan: {
        id: 'caravan',
        text: "A merchant train — wagon, oxen, driver — has been swallowed whole by the glacier. You can see crates of goods through the ice.",
        choices: [
          {
            label: 'Chip the crates free (Strength)',
            stat: 'ST',
            difficulty: 6,
            goSuccess: 'salvaged',
            goFail: 'thinice',
            successText: 'Splinters and ice fly; you haul a crate to safety.',
            failText: "The ice groans and a new crack opens under you.",
            rewardOnSuccess: { gold: 50, materials: { frost_quartz: 1, herbs: 1 } },
            hpOnFail: -10,
          },
          {
            label: 'Find a thinner pocket and dig carefully (Dexterity)',
            stat: 'DX',
            difficulty: 5,
            goSuccess: 'salvaged',
            goFail: 'thinice',
            successText: 'You ease a bag free without disturbing the ice above.',
            failText: "Hairline cracks race across the surface beneath you.",
            rewardOnSuccess: { gold: 40, materials: { frost_quartz: 1 } },
            hpOnFail: -8,
          },
        ],
      },
      thinice: {
        id: 'thinice',
        text: 'The surface is giving way. You must get off it now.',
        choices: [
          {
            label: 'Scramble to solid ground (Agility)',
            stat: 'AG',
            difficulty: 5,
            goSuccess: 'scrambled',
            goFail: 'plunged',
            successText: 'You roll clear as the section collapses.',
            failText: 'You go in up to the knee before hauling yourself out.',
            hpOnFail: -12,
          },
          {
            label: 'Spread your weight and inch back (Endurance)',
            stat: 'EN',
            difficulty: 4,
            goSuccess: 'scrambled',
            goFail: 'plunged',
            successText: 'Slow and deliberate, you reach solid ice and stand.',
            failText: "Your arms give out and you slip in.",
            hpOnFail: -10,
          },
        ],
      },
      salvaged: { id: 'salvaged', text: 'Supplies reclaimed from the deep cold.' },
      scrambled: { id: 'scrambled', text: 'Dry, just barely. You take a breath and push on.' },
      plunged: { id: 'plunged', text: 'Soaked and half-frozen, you drag yourself out and keep moving.' },
    },
  },

  // --- Frozen Caverns (additional events) --------------------------------
  ice_sculptor: {
    key: 'ice_sculptor',
    title: 'The Ice Sculptor',
    start: 'sculptor',
    nodes: {
      sculptor: {
        id: 'sculptor',
        text: 'A figure stands frozen in mid-motion — an ice sculptor, their last creation still forming around them. The sculpture is extraordinary. A faint spirit stirs within.',
        choices: [
          {
            label: 'Commune with the spirit (Wisdom)',
            stat: 'WI',
            difficulty: 5,
            goSuccess: 'touched',
            goFail: 'blank',
            successText: 'The sculptor\'s sorrow reaches you. You share a moment across the cold. Something settles on you like a gift.',
            failText: 'The spirit stirs, but you have no language for what it tries to say.',
            boonOnSuccess: 1,
          },
          {
            label: 'Appreciate the work (Charisma)',
            stat: 'CH',
            difficulty: 4,
            goSuccess: 'appreciated',
            goFail: 'blank',
            successText: 'Your genuine awe moves the spirit. It grants you what warmth it still holds.',
            failText: 'Your words are clumsy. Art and appreciation require something you don\'t have today.',
            rewardOnSuccess: { gold: 35 },
            hpOnSuccess: 12,
          },
        ],
      },
      blank: {
        id: 'blank',
        text: "The sculptor gives nothing. But the sculpture itself is flawless — ice worth harvesting.",
        choices: [
          {
            label: 'Chip fragments of the artwork free (Dexterity)',
            stat: 'DX',
            difficulty: 3,
            goSuccess: 'chipped',
            goFail: 'shattered',
            successText: 'Careful strikes yield pure, gem-clear shards.',
            failText: 'A bad blow sends a crack through the heart of the piece. The spirit departs.',
            rewardOnSuccess: { materials: { frost_quartz: 2 }, gold: 15 },
            hpOnFail: -4,
          },
          { label: 'Leave it intact and move on', go: 'pass' },
        ],
      },
      touched: { id: 'touched', text: 'The sculptor\'s gift rests on your shoulders as you walk on.' },
      appreciated: { id: 'appreciated', text: 'The spirit glows briefly, warmly, then stills. A small treasure rests at the sculpture\'s base.' },
      chipped: { id: 'chipped', text: 'Ice like frozen starlight. The sculptor would understand.' },
      shattered: { id: 'shattered', text: 'The spirit\'s last work lies in pieces. You press on, uneasy.' },
      pass: { id: 'pass', text: 'The sculptor stands, frozen and perfect, as you leave them to the cold.' },
    },
  },

  whiteout: {
    key: 'whiteout',
    title: 'The Whiteout',
    start: 'whiteout',
    nodes: {
      whiteout: {
        id: 'whiteout',
        text: "A sudden blizzard pours through a crack in the ceiling, filling the passage with blinding white. You can press forward at risk, shelter in an alcove, or endure it standing.",
        choices: [
          {
            label: 'Sprint through the blizzard (Agility)',
            stat: 'AG',
            difficulty: 7,
            goSuccess: 'through',
            goFail: 'frozen',
            successText: "Somehow you make it. Half-blind, half-dead from cold, but through.",
            failText: "The blizzard blinds you. You stumble off the path and the cold gets in.",
            rewardOnSuccess: { gold: 50, materials: { frost_quartz: 1 } },
            hpOnFail: -16,
          },
          {
            label: 'Find shelter and wait it out (Endurance)',
            stat: 'EN',
            difficulty: 5,
            goSuccess: 'sheltered',
            goFail: 'frozen',
            successText: "You find a deep alcove and press yourself into it. The storm passes.",
            failText: "No shelter deep enough. You stand in it and the cold wears you down.",
            hpOnSuccess: 8,
            hpOnFail: -10,
            staDelta: -2,
          },
        ],
      },
      frozen: {
        id: 'frozen',
        text: "The cold has bitten deep. You need to keep moving or it will kill you.",
        choices: [
          {
            label: 'Force yourself forward (Endurance)',
            stat: 'EN',
            difficulty: 4,
            goSuccess: 'through',
            goFail: 'through', // you get through either way — death would come from combat later
            successText: 'Teeth chattering, you drag yourself through the last of it.',
            failText: 'You stumble through the blizzard and collapse on the far side, shaking.',
            hpOnFail: -8,
          },
        ],
      },
      through: { id: 'through', text: 'The blizzard recedes. Silence and cold air follow you deeper.' },
      sheltered: { id: 'sheltered', text: 'The storm dies. You emerge stiff but whole.' },
    },
  },

  frozen_titan: {
    key: 'frozen_titan',
    title: 'The Frozen Titan',
    start: 'titan',
    nodes: {
      titan: {
        id: 'titan',
        text: 'A warrior of enormous stature stands frozen mid-stride, a rune-carved weapon in their hand. Their armor is intact, their expression fierce. Whatever they were guarding is ahead.',
        choices: [
          {
            label: 'Break the ice shell and take their weapon (Strength)',
            stat: 'ST',
            difficulty: 7,
            goSuccess: 'armed',
            goFail: 'backlash',
            successText: 'The ice shatters. The weapon falls free — and comes alive in your hand.',
            failText: 'The titan\'s runes flare. Something in the ice strikes back.',
            rewardOnSuccess: { gold: 70, materials: { frost_quartz: 2, iron_bar: 1 } },
            hpOnFail: -16,
            curseOnFail: true,
            requires: { minDepth: 6 },
          },
          {
            label: 'Study the runes before touching anything (Knowledge)',
            stat: 'KN',
            difficulty: 6,
            goSuccess: 'disarmed',
            goFail: 'backlash',
            successText: 'You read the ward-breaking sequence and chip the ice away safely.',
            failText: 'You misread a rune and the ward discharges.',
            rewardOnSuccess: { gold: 50, materials: { frost_quartz: 1, crystals: 1 } },
            hpOnFail: -12,
            requires: { minDepth: 6 },
          },
          {
            label: 'Bow your head and pass by',
            go: 'passed',
          },
        ],
      },
      backlash: {
        id: 'backlash',
        text: "The runes are still active. You need to either flee or endure their remaining charge.",
        choices: [
          {
            label: 'Shield yourself and ride it out (Endurance)',
            stat: 'EN',
            difficulty: 5,
            goSuccess: 'survived',
            goFail: 'survived',
            successText: 'You brace against the wall until the discharge fades.',
            failText: 'The runes drain you almost completely before going quiet.',
            hpOnFail: -10,
          },
        ],
      },
      armed: { id: 'armed', text: "The titan's weapon is yours. You feel its history in your grip." },
      disarmed: { id: 'disarmed', text: 'The titan stands weaponless, but its expression has softened. Perhaps it wanted release.' },
      survived: { id: 'survived', text: 'You straighten up, scorched and lighter, and press on.' },
      passed: { id: 'passed', text: 'The titan watches through frost. You let the dead keep their burdens.' },
    },
  },

  cold_archive: {
    key: 'cold_archive',
    title: 'The Cold Archive',
    start: 'archive',
    nodes: {
      archive: {
        id: 'archive',
        text: 'A supply cache — sleds, tools, provisions — preserved by the cold and largely forgotten. A previous expedition\'s emergency stores.',
        choices: [
          {
            label: 'Identify what\'s still usable (Knowledge)',
            stat: 'KN',
            difficulty: 2,
            goSuccess: 'identified',
            goFail: 'grabbed',
            successText: 'You spot the still-viable herbs and sealed vials at a glance.',
            failText: 'You grab what looks promising. Not all of it is.',
            rewardOnSuccess: { materials: { herbs: 2, frost_quartz: 1 }, gold: 20 },
            reward: { materials: { herbs: 1 }, gold: 10 },
          },
          {
            label: 'Crack the sealed cases (Dexterity)',
            stat: 'DX',
            difficulty: 2,
            goSuccess: 'cracked',
            goFail: 'spilled',
            successText: 'Clean breaks. The contents are intact.',
            failText: 'A vial shatters. Still, there are more.',
            rewardOnSuccess: { materials: { frost_quartz: 1 }, gold: 25 },
            reward: { gold: 10 },
          },
        ],
      },
      grabbed: {
        id: 'grabbed',
        text: "Not everything you took is useful. There's still more to sort through.",
        choices: [
          {
            label: 'Sort through the rest carefully (Wisdom)',
            stat: 'WI',
            difficulty: 2,
            goSuccess: 'sorted',
            goFail: 'move_on',
            successText: 'A second look reveals hidden value.',
            failText: 'Nothing more worth taking.',
            rewardOnSuccess: { gold: 15, materials: { herbs: 1 } },
          },
          { label: 'Leave with what you have', go: 'move_on' },
        ],
      },
      identified: { id: 'identified', text: 'Medicinals, sealed tools, and coin. The expedition was well-funded.' },
      cracked: { id: 'cracked', text: 'Frost quartz in hand — the expedition knew where to look.' },
      spilled: { id: 'spilled', text: 'Wasteful, but enough survives to be worth the stop.' },
      sorted: { id: 'sorted', text: 'Patience rewards you. Time to move.' },
      move_on: { id: 'move_on', text: 'You leave the cache to the cold.' },
    },
  },

  glacial_hermit: {
    key: 'glacial_hermit',
    title: 'The Glacial Hermit',
    start: 'hermit',
    nodes: {
      hermit: {
        id: 'hermit',
        text: "An old figure crouches in a carved-out hollow, wrapped in furs and staring into a torch. They don't look up when you arrive — but they speak. 'Sit, if you dare. Stand, if you won't.'",
        choices: [
          {
            label: 'Sit and listen (Wisdom)',
            stat: 'WI',
            difficulty: 5,
            goSuccess: 'heard',
            goFail: 'bored',
            successText: 'The hermit speaks for a long time. When you rise, something has shifted in you.',
            failText: "You can't follow their meaning. They trail off and don't speak again.",
            hpOnSuccess: 15,
            mpOnSuccess: 10,
          },
          {
            label: 'Offer something in exchange for advice (Charisma)',
            stat: 'CH',
            difficulty: 5,
            goSuccess: 'traded',
            goFail: 'bored',
            successText: 'They accept your offering with a nod and share three things that will help you.',
            failText: "They shake their head. You have nothing they want.",
            rewardOnSuccess: { gold: 30, materials: { herbs: 1 } },
            hpOnSuccess: 10,
          },
          {
            label: 'Just stand and ask a quick question',
            go: 'brief',
          },
        ],
      },
      bored: {
        id: 'bored',
        text: "The hermit has returned to staring into the torch. Perhaps they have supplies you could ask for.",
        choices: [
          {
            label: 'Ask for supplies (Charisma)',
            stat: 'CH',
            difficulty: 3,
            goSuccess: 'supplied',
            goFail: 'ignored',
            successText: 'They hand you a bundle from beside them without a word.',
            failText: 'They don\'t respond.',
            rewardOnSuccess: { materials: { herbs: 2 }, gold: 15 },
          },
          { label: 'Leave them to their flame', go: 'ignored' },
        ],
      },
      heard: { id: 'heard', text: 'The hermit falls silent. You rise, somewhat changed, without knowing quite how.' },
      traded: { id: 'traded', text: 'The hermit nods once, and you take their counsel and their warmth into the cold.' },
      brief: { id: 'brief', text: "They answer your question with one word. It's the right word. You press on." },
      supplied: { id: 'supplied', text: 'Supplies passed in silence. Worth the stop.' },
      ignored: { id: 'ignored', text: 'The torch crackles. You leave the hermit to it.' },
    },
  },

  // --- Catacombs (easy early-game events, difficulty 1–3) --------------------
  ancient_cache: {
    key: 'ancient_cache',
    title: 'The Ancient Cache',
    start: 'cache',
    nodes: {
      cache: {
        id: 'cache',
        text: 'A loose flagstone near the wall betrays a hollow underneath. Something was hidden here long ago — a traveller\'s stash, perhaps, or a grave-robber\'s take.',
        choices: [
          {
            label: 'Pry it open (Strength)',
            stat: 'ST',
            difficulty: 2,
            goSuccess: 'opened',
            goFail: 'jammed',
            successText: 'The slab grinds aside. Dust, then glinting coin.',
            failText: 'The stone catches on a buried nail; you scrape your hand.',
            rewardOnSuccess: { gold: 20, materials: { herbs: 1 } },
            hpOnFail: -4,
          },
          {
            label: 'Probe for a catch (Dexterity)',
            stat: 'DX',
            difficulty: 2,
            goSuccess: 'opened',
            goFail: 'jammed',
            successText: 'A simple latch; your fingers find it easily.',
            failText: 'A spring-clip bites your knuckle.',
            rewardOnSuccess: { gold: 25, materials: { crystals: 1 } },
            hpOnFail: -3,
          },
        ],
      },
      jammed: {
        id: 'jammed',
        text: 'There\'s still something in there. A bit of careful searching might find another way in.',
        choices: [
          {
            label: 'Feel around the edges (Knowledge)',
            stat: 'KN',
            difficulty: 2,
            goSuccess: 'opened',
            goFail: 'gave_up',
            successText: 'You find the seam and ease it free.',
            failText: 'Nothing — the stash stays buried.',
            rewardOnSuccess: { gold: 15 },
          },
          { label: 'Leave it and move on', go: 'gave_up' },
        ],
      },
      opened: { id: 'opened', text: 'Dusty coin and a desiccated herb bundle. Better than nothing.' },
      gave_up: { id: 'gave_up', text: 'The cache stays hidden. The dark keeps its secrets.' },
    },
  },

  dust_and_echoes: {
    key: 'dust_and_echoes',
    title: 'Dust and Echoes',
    start: 'passage',
    nodes: {
      passage: {
        id: 'passage',
        text: 'A low passage choked with grave-dust stretches ahead, the air thick enough to cut. You can hear something shifting far beyond — but first you have to get through.',
        choices: [
          {
            label: 'Charge through quickly (Agility)',
            stat: 'AG',
            difficulty: 2,
            goSuccess: 'clear',
            goFail: 'stumbled',
            successText: 'You dash through before the dust closes in — barely.',
            failText: 'You trip on a buried bone and breathe in a lungful.',
            rewardOnSuccess: { gold: 10 },
            hpOnFail: -5,
          },
          {
            label: 'Move slow, breathe shallow (Endurance)',
            stat: 'EN',
            difficulty: 2,
            goSuccess: 'clear',
            goFail: 'stumbled',
            successText: 'Steady and methodical, you emerge coughing but whole.',
            failText: 'Your pace slows and the dust overwhelms you.',
            rewardOnSuccess: { gold: 10 },
            hpOnFail: -4,
            staDelta: -1,
          },
        ],
      },
      stumbled: {
        id: 'stumbled',
        text: 'You\'re in the thick of it, eyes streaming. Just keep moving.',
        choices: [
          {
            label: 'Keep going no matter what (Endurance)',
            stat: 'EN',
            difficulty: 1,
            goSuccess: 'clear',
            goFail: 'clear', // you get through either way, just hurt
            successText: 'Gritting your teeth, you push to the far side.',
            failText: 'You stagger out the other end, rattled but alive.',
            hpOnFail: -5,
          },
        ],
      },
      clear: { id: 'clear', text: 'The passage opens into cleaner air. You catch your breath and press on.' },
    },
  },

  crumbling_fresco: {
    key: 'crumbling_fresco',
    title: 'The Crumbling Fresco',
    start: 'fresco',
    nodes: {
      fresco: {
        id: 'fresco',
        text: 'A faded fresco covers one wall — an old map of the tomb\'s passages, painted by whoever built this place. Sections have crumbled away, but enough remains to be useful.',
        choices: [
          {
            label: 'Study the cartography (Knowledge)',
            stat: 'KN',
            difficulty: 2,
            goSuccess: 'charted',
            goFail: 'confused',
            successText: 'You trace the surviving passages and spot a promising side-room.',
            failText: "The scale is off and the landmarks have crumbled. You can't make head or tail of it.",
            rewardOnSuccess: { gold: 25, materials: { crystals: 1 } },
          },
          {
            label: 'Trust your instincts (Wisdom)',
            stat: 'WI',
            difficulty: 2,
            goSuccess: 'sensed',
            goFail: 'confused',
            successText: 'Something about the painting speaks to you — you know which way to go.',
            failText: 'The fresco offers nothing but flaking plaster.',
            hpOnSuccess: 8,
          },
        ],
      },
      confused: {
        id: 'confused',
        text: "The map's no help. A moment spent tracing the passage walls might be more reliable.",
        choices: [
          {
            label: 'Feel along the walls (Dexterity)',
            stat: 'DX',
            difficulty: 2,
            goSuccess: 'found_path',
            goFail: 'move_on',
            successText: 'Your fingers find a tell-tale draft — there\'s a hidden nook nearby.',
            failText: 'Nothing. You move on.',
            rewardOnSuccess: { gold: 15 },
          },
          { label: 'Move on', go: 'move_on' },
        ],
      },
      charted: { id: 'charted', text: 'You slip into the side-chamber and pocket what the tomb-builders left behind.' },
      sensed: { id: 'sensed', text: 'The old instincts pay off. You move through the dark with more confidence.' },
      found_path: { id: 'found_path', text: 'A tucked alcove rewards your patience.' },
      move_on: { id: 'move_on', text: 'The fresco crumbles as you leave it behind.' },
    },
  },

  bone_chimes: {
    key: 'bone_chimes',
    title: 'The Bone Chimes',
    start: 'chimes',
    nodes: {
      chimes: {
        id: 'chimes',
        text: 'Strings of tiny bones hang across the passage — a ward, perhaps, or a trap. They clatter softly in a sourceless breeze.',
        choices: [
          {
            label: 'Pass through without disturbing them (Dexterity)',
            stat: 'DX',
            difficulty: 2,
            goSuccess: 'silent',
            goFail: 'rattled',
            successText: 'You thread between the strands without a sound.',
            failText: 'A string catches your shoulder — the bones ring out.',
            rewardOnSuccess: { gold: 15, materials: { crystals: 1 } },
            hpOnFail: -6,
          },
          {
            label: 'Speak words of respect for the dead (Charisma)',
            stat: 'CH',
            difficulty: 2,
            goSuccess: 'appeased',
            goFail: 'rattled',
            successText: 'The chimes still as if listening, then part before you.',
            failText: 'The dead are not impressed. The bones clatter and something stirs.',
            rewardOnSuccess: { gold: 10 },
            hpOnFail: -4,
          },
        ],
      },
      rattled: {
        id: 'rattled',
        text: 'The alarm is sounded. You need to move before whatever it was alerting reaches you.',
        choices: [
          {
            label: 'Sprint clear of the ward (Agility)',
            stat: 'AG',
            difficulty: 1,
            goSuccess: 'fled',
            goFail: 'caught',
            successText: 'You bolt and clear the passage before anything arrives.',
            failText: 'A skeletal hand grabs your collar before you pull free.',
            hpOnFail: -8,
          },
        ],
      },
      silent: { id: 'silent', text: 'The ward passes behind you, still and undisturbed. You find a small offering-bowl left by its maker.' },
      appeased: { id: 'appeased', text: 'The chimes part like a curtain. Whatever they were protecting, it isn\'t you.' },
      fled: { id: 'fled', text: 'You outrun the noise. Nothing follows — or nothing fast enough.' },
      caught: { id: 'caught', text: 'You tear free with a bruise and a lesson about bone wards.' },
    },
  },

  fallen_pilgrim: {
    key: 'fallen_pilgrim',
    title: 'The Fallen Pilgrim',
    start: 'pilgrim',
    nodes: {
      pilgrim: {
        id: 'pilgrim',
        text: 'A previous explorer sits slumped against the wall — long dead, but their pack is still intact. They came prepared.',
        choices: [
          {
            label: 'Search their pack carefully (Dexterity)',
            stat: 'DX',
            difficulty: 2,
            goSuccess: 'looted',
            goFail: 'sprung',
            successText: 'Patient hands find coin, salve, and a useful vial.',
            failText: 'You knock over a tripwire they set to protect their things.',
            rewardOnSuccess: { gold: 20, materials: { herbs: 1 } },
            hpOnFail: -5,
          },
          {
            label: 'Read their journal for clues (Knowledge)',
            stat: 'KN',
            difficulty: 3,
            goSuccess: 'informed',
            goFail: 'unread',
            successText: 'Their notes describe this tomb in surprising detail — and where the valuables are.',
            failText: 'The script is in a dialect you don\'t recognise.',
            rewardOnSuccess: { gold: 30, materials: { crystals: 1 } },
          },
        ],
      },
      sprung: {
        id: 'sprung',
        text: 'Trap or not, the pack is still there.',
        choices: [
          {
            label: 'Try again, more carefully (Dexterity)',
            stat: 'DX',
            difficulty: 1,
            goSuccess: 'looted',
            goFail: 'walked_on',
            successText: 'This time your fingers know what to look for.',
            failText: 'Nothing worth the bruise.',
            rewardOnSuccess: { gold: 15 },
          },
          { label: 'Leave it and move on', go: 'walked_on' },
        ],
      },
      looted: { id: 'looted', text: 'You take what you need and leave the rest. The pilgrim\'s journey is over.' },
      informed: { id: 'informed', text: 'Their notes point you toward a side-chamber you\'d have missed. Thanks, old traveller.' },
      unread: { id: 'unread', text: 'The journal stays closed. You move on.' },
      walked_on: { id: 'walked_on', text: 'Some things you leave to the dead. You press deeper.' },
    },
  },

  // --- Frozen Caverns (continued) ----------------------------------------
  aurora_pool: {
    key: 'aurora_pool',
    title: 'The Aurora Pool',
    start: 'pool',
    nodes: {
      pool: {
        id: 'pool',
        text: 'A perfectly still pool glows with refracted aurora light. Frost crystals ring its edge. Something in the water hums with residual power.',
        choices: [
          {
            label: 'Meditate on the light (Wisdom)',
            stat: 'WI',
            difficulty: 5,
            goSuccess: 'renewed',
            goFail: 'numb',
            successText: 'The aurora fills you — mind and body restored.',
            failText: 'The light is beautiful but silent. Nothing answers.',
            hpOnSuccess: 15,
            mpOnSuccess: 10,
          },
          {
            label: "Study the crystal formations (Knowledge)",
            stat: 'KN',
            difficulty: 5,
            goSuccess: 'gathered',
            goFail: 'numb',
            successText: "You identify the rarest formations and break them cleanly free.",
            failText: "Your chisel shatters a vein and the rest crumble.",
            rewardOnSuccess: { gold: 30, materials: { frost_quartz: 2, herbs: 1 } },
          },
        ],
      },
      numb: {
        id: 'numb',
        text: 'The pool gives nothing. But the cold air here is unusually still — you could rest a moment.',
        choices: [
          {
            label: 'Rest by the light (Endurance)',
            stat: 'EN',
            difficulty: 3,
            goSuccess: 'rested',
            goFail: 'cold',
            successText: 'A brief rest by the glow steadies you.',
            failText: "The stillness makes the cold bite harder.",
            hpOnSuccess: 8,
            hpOnFail: -6,
          },
          { label: 'Move on', go: 'cold', successText: 'You leave the pool and its silence behind.' },
        ],
      },
      renewed: { id: 'renewed', text: 'You rise from meditation feeling the cold less keenly.' },
      gathered: { id: 'gathered', text: 'Frost quartz in hand, you step away from the pool.' },
      rested: { id: 'rested', text: 'The aurora light was company enough. You move on steadied.' },
      cold: { id: 'cold', text: 'The pool dwindles behind you, still and silent.' },
    },
  },
};
