// ============================================================================
//  ENCOUNTERS — edit this file to add, change, or remove DnD-style text events.
// ============================================================================
//
//  HOW TO EDIT
//  -----------
//  • Each entry is `key: { title, start, nodes }`. Biomes (content/biomes.ts) list
//    which encounter keys they draw from.
//  • A node has `text` (narration) and optional `choices`. No choices = the encounter
//    ends at that node. The run reaches a checkpoint after the floor's last room.
//  • A choice with a `stat` is a check: on success it goes to `goSuccess`, on fail to
//    `goFail`; `successText`/`failText` are the result lines. A choice without a stat
//    just goes to `go`. `difficulty` ~3–8 (higher = harder), measured in stat levels. Tune freely.
//  • Loot/heals: `reward` (always) / `rewardOnSuccess`; `hpOnFail` (damage on a miss);
//    `hpOnSuccess` / `staOnSuccess` / `mpOnSuccess` (restore on a hit). Material keys
//    come from content/materials.ts.
// ============================================================================
import type { EncounterDef } from '@/engine/encounters';

export const ENCOUNTERS: Record<string, EncounterDef> = {
  // --- Catacombs ----------------------------------------------------------
  sealed_door: {
    key: 'sealed_door',
    title: 'The Sealed Door',
    start: 'door',
    nodes: {
      door: {
        id: 'door',
        text: 'A door of black iron, sealed with shifting runes, blocks the passage.',
        choices: [
          {
            label: 'Decipher the runes (Knowledge)',
            stat: 'KN',
            difficulty: 5,
            goSuccess: 'opened',
            goFail: 'locked',
            successText: 'The glyphs align and the bolts slide free.',
            failText: 'A glyph flares and lashes you with arcane backlash.',
            rewardOnSuccess: { gold: 30, materials: { crystals: 1 } },
            hpOnFail: -8,
          },
          {
            label: 'Wrench it open (Strength)',
            stat: 'ST',
            difficulty: 7,
            goSuccess: 'forced',
            goFail: 'locked',
            successText: 'Hinges scream and give way.',
            failText: 'The iron holds; you wrench your shoulder against it.',
            rewardOnSuccess: { gold: 20, materials: { iron_bar: 1 } },
            hpOnFail: -10,
          },
        ],
      },
      locked: {
        id: 'locked',
        text: 'Still sealed, the door mocks you. There must be another way through.',
        choices: [
          {
            label: 'Search for a hidden catch (Dexterity)',
            stat: 'DX',
            difficulty: 5,
            goSuccess: 'opened',
            goFail: 'giveup',
            successText: 'Your fingers find a recessed catch — click.',
            failText: 'Nothing. You squeeze through a crack instead, scraping skin.',
            rewardOnSuccess: { gold: 25 },
            hpOnFail: -6,
          },
          { label: 'Leave it and move on', go: 'giveup', successText: 'You abandon the door and press deeper.' },
        ],
      },
      opened: { id: 'opened', text: "Beyond lies a scholar's cache, long undisturbed." },
      forced: { id: 'forced', text: 'The way is open — and a fallen pack spills its contents at your feet.' },
      giveup: { id: 'giveup', text: "You move on, the cache's secrets left behind in the dark." },
    },
  },

  gatekeeper: {
    key: 'gatekeeper',
    title: 'The Gatekeeper',
    start: 'meet',
    nodes: {
      meet: {
        id: 'meet',
        text: "A spectral gatekeeper bars the way. 'A toll,' it intones, 'or a clever tongue.'",
        choices: [
          {
            label: 'Charm it (Charisma)',
            stat: 'CH',
            difficulty: 5,
            goSuccess: 'passed',
            goFail: 'angered',
            successText: 'Flattery softens the wraith; it waves you through.',
            failText: 'Your words ring hollow. It bristles with cold light.',
            rewardOnSuccess: { gold: 40 },
          },
          {
            label: 'Reason with it (Wisdom)',
            stat: 'WI',
            difficulty: 6,
            goSuccess: 'passed',
            goFail: 'angered',
            successText: 'You name the old compact; bound by it, the gatekeeper yields.',
            failText: 'It rejects your logic with a hollow laugh.',
            rewardOnSuccess: { gold: 35, materials: { crystals: 1 } },
          },
        ],
      },
      angered: {
        id: 'angered',
        text: 'The gatekeeper raises a spectral blade. This is your last chance.',
        choices: [
          {
            label: 'Slip past it (Agility)',
            stat: 'AG',
            difficulty: 6,
            goSuccess: 'passed',
            goFail: 'struck',
            successText: 'You dart through the gate before it can react.',
            failText: 'It catches you a glancing blow as you bolt through.',
            hpOnFail: -12,
          },
          {
            label: 'Force the gate (Strength)',
            stat: 'ST',
            difficulty: 7,
            goSuccess: 'forced',
            goFail: 'struck',
            successText: 'You batter the gate from its hinges.',
            failText: "The wraith's blade bites deep before you break through.",
            rewardOnSuccess: { materials: { bronze_bar: 1 } },
            hpOnFail: -14,
          },
        ],
      },
      passed: { id: 'passed', text: 'The gate swings open without a fight.' },
      forced: { id: 'forced', text: 'You break through, the gatekeeper howling into silence behind you.' },
      struck: { id: 'struck', text: 'Bloodied, you stumble past as the apparition fades.' },
    },
  },

  bone_pit: {
    key: 'bone_pit',
    title: 'The Bone Pit',
    start: 'pit',
    nodes: {
      pit: {
        id: 'pit',
        text: 'The floor gives way into a pit of clattering bones that drag at your limbs.',
        choices: [
          {
            label: 'Power through the morass (Endurance)',
            stat: 'EN',
            difficulty: 5,
            goSuccess: 'climbed',
            goFail: 'sinking',
            successText: 'Lungs burning, you haul yourself free.',
            failText: 'The bones drag you down into the cold heap.',
            rewardOnSuccess: { gold: 20, materials: { herbs: 1 } },
            hpOnFail: -8,
          },
          {
            label: 'Pick a careful path (Dexterity)',
            stat: 'DX',
            difficulty: 6,
            goSuccess: 'climbed',
            goFail: 'sinking',
            successText: 'You step from skull to skull and cross clean.',
            failText: 'A footing crumbles and you plunge in.',
            rewardOnSuccess: { gold: 25 },
            hpOnFail: -10,
          },
        ],
      },
      sinking: {
        id: 'sinking',
        text: 'Chest-deep and sinking, you need to get out — now.',
        choices: [
          {
            label: 'Thrash free by main strength (Strength)',
            stat: 'ST',
            difficulty: 5,
            goSuccess: 'climbed',
            goFail: 'crawl',
            successText: 'You burst out in a shower of bone.',
            failText: 'You barely crawl free, wrung out.',
            hpOnFail: -6,
            staDelta: -2,
          },
          {
            label: 'Stay calm and let the bones settle (Wisdom)',
            stat: 'WI',
            difficulty: 4,
            goSuccess: 'climbed',
            goFail: 'crawl',
            successText: 'You still yourself and rise; the heap releases you.',
            failText: 'Panic wins; you flounder out the hard way.',
            hpOnFail: -6,
          },
        ],
      },
      climbed: { id: 'climbed', text: 'You reach solid ground, a relic clutched from the bones.' },
      crawl: { id: 'crawl', text: 'You drag yourself out, rattled and empty-handed.' },
    },
  },

  // --- Overgrown Ruins ----------------------------------------------------
  collapsing_bridge: {
    key: 'collapsing_bridge',
    title: 'The Collapsing Bridge',
    start: 'bridge',
    nodes: {
      bridge: {
        id: 'bridge',
        text: "A rope bridge spans a ravine — and it's coming apart the moment you step on.",
        choices: [
          {
            label: 'Sprint across (Agility)',
            stat: 'AG',
            difficulty: 6,
            goSuccess: 'across',
            goFail: 'falling',
            successText: 'You race the collapse and leap to safety.',
            failText: 'A plank snaps underfoot and you drop.',
            rewardOnSuccess: { gold: 25, materials: { cloth_roll: 1 } },
            hpOnFail: -10,
          },
          {
            label: 'Cross carefully, plank by plank (Dexterity)',
            stat: 'DX',
            difficulty: 5,
            goSuccess: 'across',
            goFail: 'falling',
            successText: 'Sure-footed, you pick your way over.',
            failText: 'The boards give way beneath you.',
            rewardOnSuccess: { gold: 20 },
            hpOnFail: -8,
          },
        ],
      },
      falling: {
        id: 'falling',
        text: 'You dangle over the ravine, one hand on a fraying rope.',
        choices: [
          {
            label: 'Haul yourself up (Strength)',
            stat: 'ST',
            difficulty: 5,
            goSuccess: 'across',
            goFail: 'drop',
            successText: 'Muscles screaming, you climb to safety.',
            failText: 'Your grip fails — you fall, catching a ledge below.',
            hpOnFail: -12,
          },
          {
            label: 'Swing to a ledge (Dexterity)',
            stat: 'DX',
            difficulty: 6,
            goSuccess: 'across',
            goFail: 'drop',
            successText: 'You swing and roll onto solid stone.',
            failText: 'You misjudge it and slam into the rock.',
            hpOnFail: -12,
          },
        ],
      },
      across: { id: 'across', text: 'You reach the far side as the bridge tumbles into the dark.' },
      drop: { id: 'drop', text: 'You land hard in the gorge and limp up the far slope.' },
    },
  },

  wild_grove: {
    key: 'wild_grove',
    title: 'The Wild Grove',
    start: 'grove',
    nodes: {
      grove: {
        id: 'grove',
        text: 'A grove pulses with old magic. A guardian dryad studies you, wary.',
        choices: [
          {
            label: 'Offer respect and parley (Charisma)',
            stat: 'CH',
            difficulty: 5,
            goSuccess: 'blessed',
            goFail: 'spurned',
            successText: "The dryad warms to you and shares the grove's gifts.",
            failText: 'It deems you false and turns its back.',
            rewardOnSuccess: { gold: 30, materials: { herbs: 2 } },
            hpOnSuccess: 10,
          },
          {
            label: "Read the grove's lore (Knowledge)",
            stat: 'KN',
            difficulty: 6,
            goSuccess: 'blessed',
            goFail: 'spurned',
            successText: 'You speak the old names; the dryad bows and gifts you.',
            failText: 'You stumble the rites and offend the guardian.',
            rewardOnSuccess: { gold: 25, materials: { herbs: 1, crystals: 1 } },
            hpOnSuccess: 10,
          },
        ],
      },
      spurned: {
        id: 'spurned',
        text: 'The dryad raises coiling vines. Make amends, or flee.',
        choices: [
          {
            label: 'Soothe it with a song (Wisdom)',
            stat: 'WI',
            difficulty: 5,
            goSuccess: 'blessed',
            goFail: 'lashed',
            successText: 'Your calm reaches it; the grove relents.',
            failText: 'The vines strike before you can finish.',
            hpOnFail: -10,
          },
          {
            label: 'Back away slowly (Agility)',
            stat: 'AG',
            difficulty: 4,
            goSuccess: 'retreat',
            goFail: 'lashed',
            successText: 'You slip out of the grove unharmed.',
            failText: 'A vine catches your ankle as you go.',
            hpOnFail: -8,
          },
        ],
      },
      blessed: { id: 'blessed', text: "The grove's light knits your wounds as you pass on." },
      retreat: { id: 'retreat', text: 'You leave the grove to its guardian, no worse for it.' },
      lashed: { id: 'lashed', text: 'Whipped by thorns, you stagger out of the grove.' },
    },
  },

  // --- Catacombs (additional) ---------------------------------------------
  ossuary_hoard: {
    key: 'ossuary_hoard',
    title: 'The Ossuary Hoard',
    start: 'hoard',
    nodes: {
      hoard: {
        id: 'hoard',
        text: 'A gilded reliquary sits half-buried in a mound of bones, its locks still intact.',
        choices: [
          {
            label: 'Pick the lock (Dexterity)',
            stat: 'DX',
            difficulty: 5,
            goSuccess: 'opened',
            goFail: 'trapped',
            successText: 'The mechanism yields to your touch — the lid swings open.',
            failText: 'A spring-loaded bone-spike fires from the lock.',
            rewardOnSuccess: { gold: 45, materials: { gemstone: 1, crystals: 1 } },
            hpOnFail: -10,
          },
          {
            label: 'Identify the sigils (Knowledge)',
            stat: 'KN',
            difficulty: 5,
            goSuccess: 'opened',
            goFail: 'trapped',
            successText: 'You read a disarm sequence into the carvings — the chest clicks open.',
            failText: 'You read the wrong rune; the chest bites back.',
            rewardOnSuccess: { gold: 50, materials: { crystals: 2 } },
            hpOnFail: -8,
          },
        ],
      },
      trapped: {
        id: 'trapped',
        text: 'Bleeding, you still have a chance to pry the reliquary free.',
        choices: [
          {
            label: 'Wrench it free (Strength)',
            stat: 'ST',
            difficulty: 6,
            goSuccess: 'rich',
            goFail: 'fled',
            successText: 'You tear the reliquary loose and pocket its contents.',
            failText: 'It holds fast — you cut your losses and move on.',
            rewardOnSuccess: { gold: 30, materials: { gemstone: 1 } },
          },
          {
            label: 'Slip out before more traps fire (Agility)',
            stat: 'AG',
            difficulty: 4,
            goSuccess: 'fled',
            goFail: 'fled',
            successText: 'You back away cleanly.',
            failText: 'You stumble back; another spike grazes you.',
            hpOnFail: -6,
          },
        ],
      },
      opened: { id: 'opened', text: "The reliquary spills its wealth into your hands." },
      rich: { id: 'rich', text: 'Bloody but richer, you press deeper.' },
      fled: { id: 'fled', text: 'The hoard stays buried. Some treasure costs too much.' },
    },
  },

  whispering_crypt: {
    key: 'whispering_crypt',
    title: 'The Whispering Crypt',
    start: 'crypt',
    nodes: {
      crypt: {
        id: 'crypt',
        text: "Dozens of voices murmur from the burial niches — the dead recounting what they knew in life. You could listen, or block it out.",
        choices: [
          {
            label: 'Open your mind to the voices (Wisdom)',
            stat: 'WI',
            difficulty: 5,
            goSuccess: 'enlightened',
            goFail: 'maddened',
            successText: 'The whispers coalesce into revelation — old knowledge, freely given.',
            failText: 'The flood of voices is too much; your thoughts fracture.',
            rewardOnSuccess: { gold: 35, materials: { crystals: 1 } },
            mpOnSuccess: 8,
          },
          {
            label: 'Intone the burial rites (Charisma)',
            stat: 'CH',
            difficulty: 5,
            goSuccess: 'appeased',
            goFail: 'maddened',
            successText: 'The dead recognise a respectful tongue and quieten gratefully.',
            failText: 'Your words grate — the whispers become a shriek.',
            rewardOnSuccess: { gold: 40 },
            mpOnSuccess: 6,
          },
        ],
      },
      maddened: {
        id: 'maddened',
        text: 'The voices overwhelm you. You need to get out — or endure.',
        choices: [
          {
            label: 'Steel yourself and push through (Endurance)',
            stat: 'EN',
            difficulty: 5,
            goSuccess: 'endured',
            goFail: 'shaken',
            successText: 'You wall off the noise and stagger out the far side.',
            failText: 'The screaming follows you out.',
            hpOnFail: -8,
          },
          {
            label: 'Sprint for the exit (Agility)',
            stat: 'AG',
            difficulty: 4,
            goSuccess: 'endured',
            goFail: 'shaken',
            successText: "You're through and out before the chorus peaks.",
            failText: 'You trip in the dark and take longer than hoped.',
            hpOnFail: -6,
          },
        ],
      },
      enlightened: { id: 'enlightened', text: "The dead's knowledge fills you like cold spring water." },
      appeased: { id: 'appeased', text: 'The crypt falls silent. A calm follows you out.' },
      endured: { id: 'endured', text: 'Rattled but whole, you clear the crypt.' },
      shaken: { id: 'shaken', text: 'You stumble out, ears still ringing.' },
    },
  },

  // --- Overgrown Ruins (additional) ----------------------------------------
  toppled_idol: {
    key: 'toppled_idol',
    title: 'The Toppled Idol',
    start: 'idol',
    nodes: {
      idol: {
        id: 'idol',
        text: "A great stone idol has fallen across the passage, its altar scattered. Coins glint in the rubble.",
        choices: [
          {
            label: 'Heave the idol upright (Strength)',
            stat: 'ST',
            difficulty: 6,
            goSuccess: 'righted',
            goFail: 'cracked',
            successText: "The idol stands again — and its altar glows with rekindled offering.",
            failText: "You strain; the idol grinds but doesn't rise.",
            rewardOnSuccess: { gold: 40, materials: { stone: 1, amber_resin: 1 } },
            hpOnFail: -8,
          },
          {
            label: "Read the idol's inscriptions (Knowledge)",
            stat: 'KN',
            difficulty: 5,
            goSuccess: 'deciphered',
            goFail: 'cracked',
            successText: "You find the idol's true name and speak it — coins rise from the dust.",
            failText: "The inscription is in a dialect you don't know.",
            rewardOnSuccess: { gold: 35, materials: { stone: 1 } },
          },
        ],
      },
      cracked: {
        id: 'cracked',
        text: "The idol offers nothing obvious. Perhaps a moment of reflection would help.",
        choices: [
          {
            label: "Offer a moment's quiet reverence (Wisdom)",
            stat: 'WI',
            difficulty: 4,
            goSuccess: 'blessed',
            goFail: 'walked_on',
            successText: "The idol acknowledges the gesture — warmth spreads through you.",
            failText: "No response. Stone is just stone.",
            hpOnSuccess: 12,
          },
          { label: 'Step past and move on', go: 'walked_on', successText: 'You leave it to its fall.' },
        ],
      },
      righted: { id: 'righted', text: 'The grove-god watches from its restored plinth. You feel watched — approvingly.' },
      deciphered: { id: 'deciphered', text: 'The coins and relics settle into your pack as you press on.' },
      blessed: { id: 'blessed', text: 'The old god, even fallen, can still bless.' },
      walked_on: { id: 'walked_on', text: 'The idol remains on its side. The passage clears ahead.' },
    },
  },

  spiders_larder: {
    key: 'spiders_larder',
    title: "The Spider's Larder",
    start: 'larder',
    nodes: {
      larder: {
        id: 'larder',
        text: "Dozens of silk-wrapped bundles hang from the ceiling — the spider's prey, preserved. Some bulge with gear.",
        choices: [
          {
            label: 'Cut bundles open quietly (Dexterity)',
            stat: 'DX',
            difficulty: 5,
            goSuccess: 'looted',
            goFail: 'swarm',
            successText: 'You work fast and silent; the silk splits and your pockets fill.',
            failText: "A bundle drops with a crash — something stirs in the dark.",
            rewardOnSuccess: { gold: 35, materials: { cloth_roll: 1, herbs: 1 } },
          },
          {
            label: "Identify which bundles look richest (Knowledge)",
            stat: 'KN',
            difficulty: 4,
            goSuccess: 'looted',
            goFail: 'swarm',
            successText: 'You read the web patterns and pick the heaviest pods.',
            failText: "Your probing disturbs the web. Skittering begins overhead.",
            rewardOnSuccess: { gold: 40, materials: { cloth_roll: 2 } },
          },
        ],
      },
      swarm: {
        id: 'swarm',
        text: "Spiderlings pour from the ceiling. Fight through or run.",
        choices: [
          {
            label: 'Endure the bites and grab what you can (Endurance)',
            stat: 'EN',
            difficulty: 5,
            goSuccess: 'escaped',
            goFail: 'bitten',
            successText: 'You take a dozen stings but come away with something.',
            failText: 'The swarm drives you back empty-handed.',
            rewardOnSuccess: { gold: 20, materials: { herbs: 1 } },
            hpOnFail: -10,
          },
          {
            label: 'Bolt for the exit (Agility)',
            stat: 'AG',
            difficulty: 5,
            goSuccess: 'escaped',
            goFail: 'bitten',
            successText: 'You outrun the swarm — barely.',
            failText: 'They catch you in the doorway.',
            hpOnFail: -12,
          },
        ],
      },
      looted: { id: 'looted', text: 'Silk-threads trailing, you slip out of the larder laden.' },
      escaped: { id: 'escaped', text: "You're out. Your pulse is still racing." },
      bitten: { id: 'bitten', text: 'Marked by a dozen bites, you stagger onward.' },
    },
  },

  // --- Frozen Caverns -----------------------------------------------------
  frozen_chasm: {
    key: 'frozen_chasm',
    title: 'The Frozen Chasm',
    start: 'chasm',
    nodes: {
      chasm: {
        id: 'chasm',
        text: 'A glacier-cut chasm yawns ahead, wind howling with killing cold.',
        choices: [
          {
            label: 'Leap the gap (Strength)',
            stat: 'ST',
            difficulty: 6,
            goSuccess: 'crossed',
            goFail: 'slipped',
            successText: 'You clear the chasm and roll to a stop.',
            failText: 'You come up short, slamming into the ice wall.',
            rewardOnSuccess: { gold: 25, materials: { crystals: 1 } },
            hpOnFail: -12,
          },
          {
            label: 'Endure the cold and climb around (Endurance)',
            stat: 'EN',
            difficulty: 5,
            goSuccess: 'crossed',
            goFail: 'slipped',
            successText: 'Numb but unbroken, you work your way across.',
            failText: 'The cold saps you; you barely reach a ledge.',
            rewardOnSuccess: { gold: 20 },
            hpOnFail: -8,
            staDelta: -2,
          },
        ],
      },
      slipped: {
        id: 'slipped',
        text: 'Clinging to sheer ice, you must move before the cold claims you.',
        choices: [
          {
            label: 'Find handholds and climb (Dexterity)',
            stat: 'DX',
            difficulty: 5,
            goSuccess: 'crossed',
            goFail: 'frostbit',
            successText: 'Inch by inch, you climb to safety.',
            failText: 'Your fingers fail; you drop to a lower shelf.',
            hpOnFail: -10,
          },
          {
            label: 'Will yourself through the pain (Wisdom)',
            stat: 'WI',
            difficulty: 5,
            goSuccess: 'crossed',
            goFail: 'frostbit',
            successText: 'You focus past the cold and pull through.',
            failText: 'The cold wins this round.',
            hpOnFail: -10,
          },
        ],
      },
      crossed: { id: 'crossed', text: 'You reach the far rim, breath steaming in the still air.' },
      frostbit: { id: 'frostbit', text: 'Frostbitten and shaking, you crawl onward.' },
    },
  },

  starving_dark: {
    key: 'starving_dark',
    title: 'The Frozen Shrine',
    start: 'shrine',
    nodes: {
      shrine: {
        id: 'shrine',
        text: 'In a still hollow you find a frozen shrine, ringed by the bones of those who failed here.',
        choices: [
          {
            label: 'Forage the hollow for supplies (Knowledge)',
            stat: 'KN',
            difficulty: 5,
            goSuccess: 'supplied',
            goFail: 'empty',
            successText: 'You find cached rations and herbs, still good.',
            failText: 'Nothing but ice and old bones.',
            rewardOnSuccess: { materials: { herbs: 2 } },
            hpOnSuccess: 15,
          },
          {
            label: 'Pray at the shrine (Wisdom)',
            stat: 'WI',
            difficulty: 5,
            goSuccess: 'blessed',
            goFail: 'empty',
            successText: 'A faint warmth answers — the shrine restores you.',
            failText: 'The shrine is silent and dead.',
            hpOnSuccess: 12,
            mpOnSuccess: 6,
          },
        ],
      },
      empty: {
        id: 'empty',
        text: 'Cold and empty-handed, you search for any way onward.',
        choices: [
          {
            label: 'Rest a moment to gather strength (Endurance)',
            stat: 'EN',
            difficulty: 4,
            goSuccess: 'rested',
            goFail: 'weary',
            successText: 'A brief rest steadies you.',
            failText: "There's no rest to be had in this cold.",
            hpOnSuccess: 10,
            staOnSuccess: 2,
          },
          { label: 'Push on immediately', go: 'weary', successText: 'You waste no time and move deeper.' },
        ],
      },
      supplied: { id: 'supplied', text: 'Restored, you shoulder your finds and go on.' },
      blessed: { id: 'blessed', text: 'Renewed, you leave the shrine to the dark.' },
      rested: { id: 'rested', text: 'Steadier now, you press into the cold.' },
      weary: { id: 'weary', text: 'Weary but alive, you continue.' },
    },
  },

  // --- Frozen Caverns (additional) ----------------------------------------
  buried_caravan: {
    key: 'buried_caravan',
    title: 'The Buried Caravan',
    start: 'caravan',
    nodes: {
      caravan: {
        id: 'caravan',
        text: "A merchant train — wagon, oxen, driver — has been swallowed whole by the glacier. You can see crates of goods through the ice.",
        choices: [
          {
            label: 'Chip the crates free (Strength)',
            stat: 'ST',
            difficulty: 6,
            goSuccess: 'salvaged',
            goFail: 'thinice',
            successText: 'Splinters and ice fly; you haul a crate to safety.',
            failText: "The ice groans and a new crack opens under you.",
            rewardOnSuccess: { gold: 50, materials: { frost_quartz: 1, herbs: 1 } },
            hpOnFail: -10,
          },
          {
            label: 'Find a thinner pocket and dig carefully (Dexterity)',
            stat: 'DX',
            difficulty: 5,
            goSuccess: 'salvaged',
            goFail: 'thinice',
            successText: 'You ease a bag free without disturbing the ice above.',
            failText: "Hairline cracks race across the surface beneath you.",
            rewardOnSuccess: { gold: 40, materials: { frost_quartz: 1 } },
            hpOnFail: -8,
          },
        ],
      },
      thinice: {
        id: 'thinice',
        text: 'The surface is giving way. You must get off it now.',
        choices: [
          {
            label: 'Scramble to solid ground (Agility)',
            stat: 'AG',
            difficulty: 5,
            goSuccess: 'scrambled',
            goFail: 'plunged',
            successText: 'You roll clear as the section collapses.',
            failText: 'You go in up to the knee before hauling yourself out.',
            hpOnFail: -12,
          },
          {
            label: 'Spread your weight and inch back (Endurance)',
            stat: 'EN',
            difficulty: 4,
            goSuccess: 'scrambled',
            goFail: 'plunged',
            successText: 'Slow and deliberate, you reach solid ice and stand.',
            failText: "Your arms give out and you slip in.",
            hpOnFail: -10,
          },
        ],
      },
      salvaged: { id: 'salvaged', text: 'Supplies reclaimed from the deep cold.' },
      scrambled: { id: 'scrambled', text: 'Dry, just barely. You take a breath and push on.' },
      plunged: { id: 'plunged', text: 'Soaked and half-frozen, you drag yourself out and keep moving.' },
    },
  },

  aurora_pool: {
    key: 'aurora_pool',
    title: 'The Aurora Pool',
    start: 'pool',
    nodes: {
      pool: {
        id: 'pool',
        text: 'A perfectly still pool glows with refracted aurora light. Frost crystals ring its edge. Something in the water hums with residual power.',
        choices: [
          {
            label: 'Meditate on the light (Wisdom)',
            stat: 'WI',
            difficulty: 5,
            goSuccess: 'renewed',
            goFail: 'numb',
            successText: 'The aurora fills you — mind and body restored.',
            failText: 'The light is beautiful but silent. Nothing answers.',
            hpOnSuccess: 15,
            mpOnSuccess: 10,
          },
          {
            label: "Study the crystal formations (Knowledge)",
            stat: 'KN',
            difficulty: 5,
            goSuccess: 'gathered',
            goFail: 'numb',
            successText: "You identify the rarest formations and break them cleanly free.",
            failText: "Your chisel shatters a vein and the rest crumble.",
            rewardOnSuccess: { gold: 30, materials: { frost_quartz: 2, herbs: 1 } },
          },
        ],
      },
      numb: {
        id: 'numb',
        text: 'The pool gives nothing. But the cold air here is unusually still — you could rest a moment.',
        choices: [
          {
            label: 'Rest by the light (Endurance)',
            stat: 'EN',
            difficulty: 3,
            goSuccess: 'rested',
            goFail: 'cold',
            successText: 'A brief rest by the glow steadies you.',
            failText: "The stillness makes the cold bite harder.",
            hpOnSuccess: 8,
            hpOnFail: -6,
          },
          { label: 'Move on', go: 'cold', successText: 'You leave the pool and its silence behind.' },
        ],
      },
      renewed: { id: 'renewed', text: 'You rise from meditation feeling the cold less keenly.' },
      gathered: { id: 'gathered', text: 'Frost quartz in hand, you step away from the pool.' },
      rested: { id: 'rested', text: 'The aurora light was company enough. You move on steadied.' },
      cold: { id: 'cold', text: 'The pool dwindles behind you, still and silent.' },
    },
  },
};
